apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: postgres-db
resources:
  - ../apps/base/postgres.yaml
configMapGenerator:
  - name: coursework-config
    literals:
      - DB_HOST=coursework-db-rw.coursework-ns.svc.cluster.local
      - DB_PORT=5432
      - DB_NAME=app
      - DB_USER=app

