apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - postgres.yaml
  - namespace.yaml
configMapGenerator:
  - name: coursework-config
    literals:
      - DB_TYPE=postgresdb
      - DB_POSTGRESDB_HOST=postgres-db-rw
      - DB_POSTGRESDB_PORT=5432
      - DB_POSTGRESDB_DATABASE=mydatabase