apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - helm-app.yaml
configMapGenerator:
  - name: coursework-config
    literals:
      - DB_TYPE=postgresdb
      - DB_HOST=postgres-db-rw
      - DB_PORT=5432
      - DB_NAME=mydatabase
      - DB_USER=myuser

