apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - postgres.yaml
  - helm-app.yaml
configMapGenerator:
  - name: coursework-config
    literals:
      - DB_HOST=coursework-db-rw.coursework-ns.svc.cluster.local
      - DB_PORT=5432
      - DB_NAME=app
      - DB_USER=app

