apiVersion: v1
kind: Secret # Secret с доступами к БД.
metadata:
  name: coursework-db-secret
data:
  username: {{ .Values.DB_USER| b64enc }}
  password: {{ .Values.DB_PASS| b64enc }}
type: kubernetes.io/basic-auth