apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: prodaction-chart
  namespace: flux-system
spec:
  interval: 10m0s
  targetNamespace: production
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./clusters/apps/overlays/production"
  prune: true
  timeout: 1m0s
