apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: staging-chart
  namespace: flux-system
spec:
  dependsOn:
    - name: dbpg-operator
  interval: 10m0s
  targetNamespace: staging
  sourceRef:
    kind: GitRepository
    name: flux-system
  path: "./clusters/apps/overlays/staging"
  prune: true
  timeout: 1m0s
